<?php

print "<input type=hidden name=sei value=$sei>";
print "<input type=hidden name=mei value=$mei>";
print "<input type=hidden name=penname value=$penname>";
print "<input type=hidden name=mail value=$mail>";
print "<input type=hidden name=tel value=$tel>";
print "<input type=hidden name=age value=$age>";
print "<input type=hidden name=sex value=$sex>";
print "<input type=hidden name=birthy value=$birthy>";
print "<input type=hidden name=place value=$place>";
print "<input type=hidden name=postal value=$postal>";
print "<input type=hidden name=mibun[] value=$mibun>";
print "<input type=hidden name=by_id value=$by_id>";

?>
